<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>Vigilance</PackageId>
    <Version>0.0.18</Version>
    <Authors>Samael Heaven</Authors>
    <Description>2D Game Engine</Description>
    <RepositoryUrl>https://github.com/SamaelHeaven/Vigilance</RepositoryUrl>
    <PackageReadmeFile>README.MD</PackageReadmeFile>
    <PackageLicenseExpression>Zlib</PackageLicenseExpression>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
    <MSBuildEnableWorkloadResolver>false</MSBuildEnableWorkloadResolver>
    <LibsPath>$([MSBuild]::NormalizeDirectory('$(MSBuildThisFileDirectory)..\..\libs\'))</LibsPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Box2D.NET.Release" Version="3.1.0" />
    <PackageReference Include="FlexLayoutSharp" Version="1.0.0" />
    <PackageReference Include="FreeTypeSharp" Version="3.0.1" />
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageReference Include="LinkDotNet.StringBuilder" Version="3.4.1" />
    <PackageReference Include="Raylib-cs" Version="8.0.0" />
    <PackageReference Include="ZLinq" Version="1.5.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference
      Include="..\Vigilance.Codegen\Vigilance.Codegen.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
    />
  </ItemGroup>
  <ItemGroup>
    <None Include="Vigilance.props" Pack="true" PackagePath="build\Vigilance.props" />
    <None Include="$(MSBuildThisFileDirectory)..\..\README.MD" Pack="true" PackagePath="README.MD" />
    <None Include="$(LibsPath)\**\*" Pack="true" PackagePath="build\libs\" />
    <EmbeddedResource Include="Resources\**\*" />
  </ItemGroup>
</Project>
