name: Publish NuGet Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Bump version number
        run: |
          CURRENT_VERSION=$(grep -oPm1 "(?<=<Version>)(.*)(?=</Version>)" src/Vigilance/Vigilance.csproj)
          echo "Current version: $CURRENT_VERSION"

          IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"
          PATCH_VERSION=${VERSION_PARTS[2]}

          NEW_PATCH_VERSION=$((PATCH_VERSION + 1))
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$NEW_PATCH_VERSION"

          sed -i "s|<Version>.*</Version>|<Version>$NEW_VERSION</Version>|" src/Vigilance/Vigilance.csproj
          echo "Updated version to: $NEW_VERSION"

          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Bump version to $NEW_VERSION [skip ci]" || echo "No changes to commit"
          git push

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack the NuGet package
        run: dotnet pack --configuration Release --output ./nupkgs

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
